### ISSUE TITLE
Update agdk-eframe demo to latest IME branches from lucas

### ISSUE THREAD

**Issue by jb55** [damus-io/android#77]
Lucas has a updated branches for v0.26 (see comment here): 

- https://github.com/damus-io/android/issues/60#issuecomment-2022502072

Let's get these running in the agdk-eframe demo first to confirm it is working

**Comment by jb55** [comment]
Got v0.26.2 to compile here: https://github.com/jb55/rust-android-examples/tree/ime_0.26.2

but currently crashes on launch. Need to figure out how to debug before continuing.

**Comment by jb55** [comment]
logcat:

```
04-08 18:03:09.143 11474 11474 E lfit.agdkeframe: No implementation found for long com.google.androidgamesdk.GameActivity.loadNativeCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, android.content.res.AssetManager, byte[]) (tried Java_com_google_androidgamesdk_GameActivity_loadNativeCode and Java_com_google_androidgamesdk_GameActivity_loadNativeCode__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Landroid_content_res_AssetManager_2_3B) - is the library loaded, e.g. System.loadLibrary?
04-08 18:03:09.143 11474 11474 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-08 18:03:09.148 11474 11474 E AndroidRuntime: FATAL EXCEPTION: main
04-08 18:03:09.148 11474 11474 E AndroidRuntime: Process: co.realfit.agdkeframe, PID: 11474
04-08 18:03:09.148 11474 11474 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for long com.google.androidgamesdk.GameActivity.loadNativeCode(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, android.content.res.AssetManager, byte[]) (tried Java_com_google_androidgamesdk_GameActivity_loadNativeCode and Java_com_google_androidgamesdk_GameActivity_loadNativeCode__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Landroid_content_res_AssetManager_2_3B) - is the library loaded, e.g. System.loadLibrary?
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at com.google.androidgamesdk.GameActivity.loadNativeCode(Native Method)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at com.google.androidgamesdk.GameActivity.onCreate(GameActivity.java:265)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at co.realfit.agdkeframe.MainActivity.onCreate(MainActivity.java:63)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8935)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8904)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8893)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
04-08 18:03:09.148 11474 11474 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
04-08 18:03:09.157  1345 11513 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-08 18:03:09.158  1345  3073 D Debug   : low && ship && 3rdparty app crash, do not dump
04-08 18:03:09.159  1345 11514 W ActivityManager: crash : co.realfit.agdkeframe,10236
04-08 18:03:09.159  1345  3073 W ActivityTaskManager:   Force finishing activity co.realfit.agdkeframe/.MainActivity
```

**Comment by jb55** [comment]
Looks like this is caused by a version mismatch between GameActivity 2.0 (which is expected in the latest version android-activity). So I think if I update my local NDK it should be ok? Will try this.

**Comment by jb55** [comment]
Looks like that was the issue, updating to game-activity 2.0.2 fixes the crash.

Now I'm seeing weird behaviours:

- No words are highlighted, and there is no autocompletion
- Backspace and enter are sent twice

not sure if you ran into this on 0.26.2 @lucasmerlin ?

My demo tinkering is here:

```
git clone -b ime_0.26.2 https://github.com/jb55/rust-android-examples
git clone -b ime_0.26.2 https://github.com/jb55/egui
```

I'm also on `winit` @ hp-fixes-0.29.x and `android-activity` @ hp_changes_2

**Comment by jb55** [comment]
range-diff between hp_improvements_0.26 and ime_0.26.2:

`git range-diff hp_improvements_0.26...ime_0.26.2`

```
 1:  ee7fb477986b <  -:  ------------ add with_taskbar to viewport builder (#3958)
 2:  b35a7dd7de00 <  -:  ------------ Add scroll bar visibility option to Table widget (#3981)
 3:  377f86efb523 =  1:  26a87715f275 egui: Fixed window title bar incorrect handling spacing (#3995)
 4:  21f08afcbbef =  2:  826b1ac80d58 egui_glow: Only disable sRGB framebuffer on supported platforms (#3994)
 5:  15370bbea0b4 <  -:  ------------ Add F21 to F35 key bindings (#4004)
 -:  ------------ >  3:  a829fff19c5b Make `on_disabled_hover_ui` respect `tooltip_delay` (#4012)
 -:  ------------ >  4:  a415aa4bc686 Update to document-features 0.2.8 (#4003)
 -:  ------------ >  5:  1fe0f2417ab8 Improve panic message in egui-wgpu when failing to create buffers (#3986)
 -:  ------------ >  6:  820a3baf3017 egui demo: Fix space reserved for source code link (#3983)
 -:  ------------ >  7:  db00dc6ea546 Fix `TextEdit` being too short whenever there is horizontal margin (#4005)
 -:  ------------ >  8:  df7e4a5db64c Fix `Response::interact` and `Ui:interact_with_hovered` (#4013)
 -:  ------------ >  9:  45154fc1c839 Fix: `Response.interact_pointer_pos` is `Some` on click and drag released (#4014)
 -:  ------------ > 10:  12749f3b5adb Take clip_rect into account when storing widget rects (#4020)
 -:  ------------ > 11:  6e4dab97fb50 Revert semver-breaking change, and replace with temporary HACK
 -:  ------------ > 12:  109c0a86952a Revert renaming a field in `WidgetRect` to avoid semver breakage
 -:  ------------ > 13:  9aac3ef40692 Revert hello_world example
 -:  ------------ > 14:  0d17b6748d8c egui: Fix custom `Window` `Frame`s (#4009)
 -:  ------------ > 15:  a8501c963dba Release 0.26.1 - Bug Fixes
 -:  ------------ > 16:  2f572197efe9 Update memoffset to 0.9.0, arboard to 3.3.1, and remove egui_glow's needless dependency on pure_glow's deps  (#4036)
 -:  ------------ > 17:  b64e329cb7a7 `eframe`: Add `winuser` feature to `winapi` to fix unresolved import (#4037)
 -:  ------------ > 18:  ed5fe015359d Add another check to Windows CI (#4038)
 -:  ------------ > 19:  1ce4f0547226 Avoid interacting twice when not required (#4041)
 -:  ------------ > 20:  309586b42cc8 Release 0.26.2 - Response.interact/context_menu fix
 6:  6cf77dd0ac05 = 21:  a18c816bbe8e Expose center position in MultiTouchInfo
 7:  85dfff9b7e8b = 22:  2c3cb458036f Increase scroll area friction
 8:  8c6479ff9ff5 = 23:  f1f6cffc7a80 Add option to specify persistence path
 9:  eba2e3f8896d = 24:  04f76de5ae11 Remove WaitUntil fix since it seems to be working now
10:  e58b66f36f97 = 25:  b4aa3b7e141f Ime support
```

Seems more likely that winit changes broke something?

```
  1 monad> g range-diff lucas/v0.28.x_ime_support...lucas/hp-fixes-0.29.x  | grep -i android
 30:  305a302a98ae <   -:  ------------ Add basic android ime support
  -:  ------------ >  75:  4a36741f9cca On Android, change default implementation to ignore volume keys and let operating system handle them (#2748)
  -:  ------------ >  95:  7929999c1c9b Android: rework keycode handling (#2890)
  -:  ------------ > 136:  7a954c7e0898 Android: Implement EventLoopExtPumpEvents and EventLoopExtRunOnDemand
  -:  ------------ > 172:  7451c4b88c7c Android: Support unicode character mapping + dead keys
  -:  ------------ > 178:  65c2482d74fd Pin android-activity git dependency
  -:  ------------ > 181:  80d1e49354cd Use beta versions of android crates
  -:  ------------ > 218:  709929fcab0c Pass force on touch events on android
  -:  ------------ > 225:  4385c17cbb3e Make DeviceId contain device id's on Android
  -:  ------------ > 235:  5788319632b4 Add Occluded and MemoryWarning events for iOS/Android
  -:  ------------ > 245:  f2edd235428e Upgrade to `ndk 0.8`, `ndk-sys 0.5` + `android-activity 0.5` releases
  -:  ------------ > 285:  7aa202b872a3 Make Android docs build on docs.rs (#3236)
  -:  ------------ > 337:  9576d91dfe25 Fix stylus input on android
```

**Comment by jb55** [comment]
video of the broken input:

https://cdn.jb55.com/s/broken-input.mp4

**Comment by lucasmerlin** [comment]
For the autocomple to work you have to set the input type, I do that somewhere in my fork of android Activity (can't check for the specific spot right now, sorry)

**Comment by jb55** [comment]
I wonder if there are bugs in GameActivity 2.0.2:

here's a few fix commits I found in v2..v3
`git log --reverse -p --grep fix --no-merges cf9df6e927bafbc496e160830d378600c53bddc8.. -- game-text-input`

```
92c7a40427ea fix hardware keyboard support
140cb55df2f4 fix for hardware and software keyboards being out of sync
cd73cee28208 fixed multiline mode
d238783e3497 add physical volume buttons to the ignore list for GameTextInput
b2f598f0ad85 fix GameTextInput editing functions
18fc8e25c509 fix a race condition in GameTextInput
dfca49441b07 refactor GameActivity and GameTextInput interfaces
f1f286b6486e fix text deletion in GameTextInput
094b21ff9b45 fix selection when typing with hardware keyboard
8bee4e62f5c6 fixed state updates propagation
80739abf3623 bump GameActivity and GameTextInput to 3.0.3
```

log: https://cdn.jb55.com/s/4f6ef8bbbd88ebfc.txt

We may need to update android-activity to gameactivity 3 to see if that's the case.

Looks like the API changes are in here:

https://cdn.jb55.com/s/be4dbb351d42c4e7.txt

**Comment by jb55** [comment]
not sure if you've looked at GameActivity 3 yet @rib or have any insight here :eyes:

**Comment by jb55** [comment]
> @lucasmerlin: For the autocomplete to work you have to set the input type

ok I'll try that, thanks!

**Comment by jb55** [comment]
@lucasmerlin that worked.

applying

```patch
commit 3eac5df96a51f32328849520a48f214bca19933e
Author: Lucas Meurer <lucasmeurer96@gmail.com>
Date:   Tue Aug 1 14:17:01 2023 +0200

    Set editor info

diff --git a/android-activity/src/game_activity/mod.rs b/android-activity/src/game_activity/mod.rs
index 065191c11f2f..2d813cfa6835 100644
--- a/android-activity/src/game_activity/mod.rs
+++ b/android-activity/src/game_activity/mod.rs
@@ -459,6 +459,7 @@ impl AndroidAppInner {
             } else {
                 0
             };
+            ffi::GameActivity_setImeEditorInfo(activity, 1 | 16384, 0, 0);
             ffi::GameActivity_showSoftInput(activity, flags);
         }
     }
```

fixed the double-enter and backspace issue.

**Comment by jb55** [comment]
I finished what I wanted to do here. continuing onto:

- https://github.com/damus-io/android/issues/78

**Comment by jb55** [comment]
it doesn't look like there is a `GameActivity_setImeEditorInfo` interface in android-activity with typed bit flags. I will look into adding this if that's ok @rib
